config/routes.rb
Rails.application.routes.draw do
  resources :kontildondits
  mount ForestLiana::Engine => '/forest'
  resources :podcasts
  resources :books
  resources :badas
  resources :abonnes
  resources :rubriques,  :path => "chroniques"
  get '/kitafetoi', to: 'kitafetois#index', as: :kitafetois
  resources :kitafetois
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'thematiques' => 'podcasts#thematiques', as: :thematiques
  get 'partners' => 'pages#partners', as: :partners
  get 'abonnement' => 'pages#abonnement', as: :abonnement
  get 'updatecard' => 'pages#updatecard', as: :updatecard
  get 'mentions' => 'pages#mentions', as: :mentions
  get '/intervenant/:id', to: 'intervenants#show', as: 'intervenant'
  resources :charges
  resources :updatecards
  get 'thanks', to: 'charges#thanks', as: 'thanks'
  get 'soutiens', to: 'pages#soutiens', as: 'soutiens'
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
  get 'lettre' => 'pages#lettre', as: :lettre
  get 'lettretest' => 'pages#lettretest', as: :lettretest
end

app/models/abonne.rb
class Abonne < ApplicationRecord
	has_many :intervenants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bada.rb
class Bada < ApplicationRecord
	belongs_to :podcast
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :podcast
	belongs_to :intervenant
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/intervenant.rb
class Intervenant < ApplicationRecord
	has_many :books
	has_many :podcasts
	has_many :abonnes
	has_many :rubriques
end

app/models/kitafetoi.rb
class Kitafetoi < ApplicationRecord
	has_many :intervenants
end

app/models/mailchimp.rb
class Mailchimp < ApplicationRecord
end

app/models/podcast.rb
class Podcast < ApplicationRecord
	has_many :books
	has_many :intervenants
end

app/models/public.rb
class Public < ApplicationRecord

	
end

app/models/rubrique.rb
class Rubrique < ApplicationRecord
	belongs_to :intervenant
end

app/controllers/abonnes_controller.rb
class AbonnesController < ApplicationController
  before_action :set_abonne, only: [:show, :edit, :update, :destroy]
  before_action :set_link

  def index
    @abonnes = Abonne.all.order(created_at: :desc).page(params[:page]).per(5)
  end

  def show
  end

  def new
    @abonne = Abonne.new
  end

  def edit
  end

  def create
    @abonne = Abonne.new(abonne_params)
    
    if @abonne.save
      redirect_to @abonne, notice: 'Podcast was successfully created.'
    else
      render :new
    end
  end

  def update
    if @abonne.update(abonne_params)
      redirect_to @abonne, notice: 'Podcast was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @abonne.destroy
    redirect_to pabonnes_url, notice: 'Podcast was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abonne
      @abonne = Abonne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def abonne_params
      params.require(:abonne).permit(:title, :lien, :title1, :intro1, :title2, :intro2)
    end

    def set_link
      @public_link = Public.where(live: true).order(created_at: :desc).first
    end

end

app/controllers/badas_controller.rb
class BadasController < ApplicationController
  before_action :set_bada, only: [:show, :edit, :update, :destroy]
  before_action :set_link

  def index
    @badas = Bada.all.includes(:podcast).order('podcasts.created_at desc').page(params[:page]).per(5)
  end

  def show
  end

  def new
    @bada = Bada.new
  end

  def edit
  end

  def create
    @bada = Bada.new(bada_params)
    
    if @bada.save
      redirect_to @bada, notice: 'Bada was successfully created.'
    else
      render :new
    end
  end

  def update
    if @bada.update(bada_params)
      redirect_to @bada, notice: 'Bada was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @bada.destroy
    redirect_to badas_url, notice: 'Bada was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bada
      @bada = Bada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bada_params
      params.require(:bada).permit(:title, :lien, :podcast_id, :transcript)
    end

    def set_link
      @public_link = Public.where(live: true).order(created_at: :desc).first
    end 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :set_link

  def index
    @books = Book.all.includes(:podcast).order('podcasts.created_at desc').page(params[:page]).per(12)
  end

  def show
    
  end

  def new
    @book = book.new
  end

  def edit
  end

  def create
    @book = book.new(book_params)
    
    if @book.save
      redirect_to @book, notice: 'book was successfully created.'
    else
      render :new
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: 'book was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:titre, :intervenant_id, :podcast_id, :description, :image)
    end

    def set_link
      @public_link = Public.where(live: true).order(created_at: :desc).first
    end 
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :address => params[:order_address],
      :card  => params[:stripeToken],
      :plan => params[:stripePlan]
    )

    # charge = Stripe::Charge.create(
    #   customer:     customer.id,
    #   amount:       params[:stripeAmount],
    #   description:  'Le Nouvel Esprit public',
    #   currency:     'eur'
    # )

    UserMailer.booking_confirmation(params[:stripeEmail]).deliver
    UserMailer.booking(params[:stripeEmail]).deliver

    redirect_to thanks_path

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to charges_path
  end

  def thanks
  end

  def plans
    @stripe_list = Stripe::Plan.all
    @plans = @stripe_list[:data]
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :set_link, :set_mailchimp


	def home
		@podcast = Podcast.all.order(created_at: :desc).first
	end
	
	def partners
	end

	def abonnement
	end

	def updatecard
	end

	def mentions
	end

	def soutiens
	end

	def lettre
	end

	def lettretest
	end

	def subscribed
    UserMailer.subscribe_confirmation(params[:email]).deliver
    UserMailer.subscribe(params[:email]).deliver
    redirect_to :action => "home"
	end

	def letsencrypt
	  render text: params[:id]+'.ylwsIZ1qM8410SY4fhGjVuvDfZoYpC6DvIEe4BSXSek'
	end

	private
    def set_link
      @public_link = Public.where(live: true).order(created_at: :desc).first
    end

    def set_mailchimp
      @mailchimp_link = Mailchimp.order(created_at: :desc).first
    end 

end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/kontildits_helper.rb
module KontilditsHelper
end

app/helpers/kontildondits_helper.rb
module KontildonditsHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/rubriques_helper.rb
module RubriquesHelper
end

app/views/abonnes/index.html.erb
<div class="container page-authentification">

  <span style="font-size: 27px;"><strong class="first">Kitafétoi - accès pour nos généreux soutiens</strong></span>
  <p style="padding-right: 50px;" class="aerian">Kitafétoi ?, supplément à parution aléatoire du Nouvel Esprit public, est un dialogue entre Philippe Meyer et un(e) invité(e) qui évoque les rencontres qui, de l’enfance à l’âge mûr, lui ont permis de s’accomplir. Kitafétoi ? est proposé en exclusivité pendant deux semaines aux abonnés du Nouvel Esprit public et aux personnes qui soutiennent notre podcast.</p>
  <div class="result">
    <div class="article-search archive">
      <article class=" on" style="height: 223px;">
        <div class="entry-content">
          <div>
            <h2>Bernard Pivot</h2>
            <iframe width="100%" height="150" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/480605085&color=%239D3934&auto_play=false&hide_related=true&show_comments=false&show_user=false&show_reposts=false&show_teaser=false&visual=false"></iframe>
            <p class="aerian">Premier des hôtes de Kitafétoi ? <strong>Bernard Pivot</strong> évoque celles et ceux qui ont permis à un petit garçon solitaire, renfermé et falot de devenir un octogénaire plébiscité par ses concitoyens, à un journaliste sans qualités autres que le travail de devenir une figure de sa profession, à un animateur cité en exemple de ne pas se changer en statue et de préférer explorer toutes les voies qui se sont ouvertes à lui jusqu’à celle qui l’a conduit aujourd’hui sur scène avec « Au Secours ! Les Mots m’ont mangé ».</p>
          </div>
        </div>
        <span class="icon-top"><i class="sprite etat"></i></span>
      </article>
      <article class=" on" style="height: 223px;">
        <div class="entry-content">
          <div>
            <h2>Roselyne Bachelot</h2>
            <iframe width="100%" height="150" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/480609927&color=%239D3934&auto_play=false&hide_related=false&show_comments=false&show_user=false&show_reposts=false&show_teaser=false"></iframe>
            <p class="aerian">Au cours de la deuxième édition de ce supplément, <strong>Roselyne Bachelot</strong> raconte les figures qui lui ont transmis en héritage comme deux évidences le féminisme et le gaullisme. Un féminisme nourri d’exemples découverts dans les deux générations de femmes qui l’ont élevée et un gaullisme façonné par des modèles issus de toutes les formes de résistance. Ce double legs a permis à la future ministre de la Santé d’ébranler quelques forteresses, à commencer par celles de la politique, puis de conquérir sa place à la radio puis à la télévision, le tout grâce à (ou en dépit) des personnalités dont elle brosse le portrait.</p>
          </div>
        </div>
        <span class="icon-top"><i class="sprite etat"></i></span>
      </article>

    </div>
  </div>
</div>

app/views/badas/_form.html.erb
<%= form_for(bada) do |f| %>
  <% if bada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bada.errors.count, "error") %> prohibited this bada from being saved:</h2>

      <ul>
      <% bada.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :lien %>
    <%= f.text_field :lien %>
  </div>

  <div class="field">
    <%= f.label :podcast_id %>
    <%= f.text_field :podcast_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badas/edit.html.erb
<h1>Editing Bada</h1>

<%= render 'form', bada: @bada %>

<%= link_to 'Show', @bada %> |
<%= link_to 'Back', badas_path %>

app/views/badas/index.html.erb
<div class="container page-authentification">

  <span style="font-size: 27px;"><strong class="first">Des badas </strong> pour approfondir les discussions en public</span>
  <p>Dans « Le Voleur dans la maison vide », Jean-François Revel rappelle que, dans le Marseille de son enfance, Bada, était le le nom donné au supplément que les marchands de glace étaient moralement tenus d'offrir aux acheteurs de leurs cornets…
  <br>Nos Badas, en  ces temps de confinement, ce sont des suppléments à nos conversations hebdomadaires. Entretiens, thématiques, documents, ils sont une autre façon de contribuer à la compréhension de la situation et à la réflexion sur ses conséquences et ses issues.</p>
  <p>Amitiés,<br> Ph. M.</p>
  <div class="result">
    <script src='//w.soundcloud.com/player/api.js'></script>
    <div class="article-search archive">
      <% @badas.each do |bada| %>
        <article>
          <h3>
            <%= link_to bada.title + " du " + bada.podcast.created_at.strftime("%d-%m-%Y"), bada, class: 'author' %>
          </h3>
          <span class="num-date"></span>
          <iframe src="<%= bada.lien %>/embed" style="width: 100%; height: 200px; border: 0 none;" scrolling="no"></iframe>
          <%= link_to "Voir le podcast à l'origine de ce bada", bada.podcast, class: 'author' %>
        </article>
        <br>
      <% end %>
      <div class="nav-article">                  
        <%= paginate @badas %>
      </div>
    </div>
  </div>
</div>

app/views/badas/new.html.erb
<h1>New Bada</h1>

<%= render 'form', bada: @bada %>

<%= link_to 'Back', badas_path %>

app/views/badas/show.html.erb
<div class="container clearfix">
  <div class="table articles  page-edito ">
    <section class="left-article table-cell">
      <!-- left-article -->
      <article class="clearfix edito">
        <div class="table">
          <div class="body-edito table-cell">
            <header>
              <h1 class='podcast-title'><%= @bada.title %></h1>
            </header>
            <iframe src="<%= @bada.lien %>/embed" style="width: 100%; height: 200px; border: 0 none;" scrolling="no"></iframe>
            <%= link_to "Voir le podcast à l'origine de ce bada", @bada.podcast, class: 'author' %>
          </div>
        </div>
        <% if @bada.transcript %>
          <h3 id="kontildondit1">Kontildondit ?</h3>
          <p class='intro-podcast aerian' style="font-family:ArcherLight;" ><%= @bada.transcript.html_safe %></p>
        <% end %>
      </article>
      <!-- last article -->
      <!-- liste journal -->
      <div class="last-num">
        <ul class="clearfix">
          <li class="view-all"><%= link_to 'VOIR TOUS LES BADAS', badas_path %></li>
        </ul>
      </div>
    </section>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %>
    <%= f.text_field :titre %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="form-group">
    <%= f.label :image %>    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :podcast_id %>
    <%= f.text_field :podcast_id %>
  </div>

  <div class="field">
    <%= f.label :intervenant_id %>
    <%= f.text_field :intervenant_id %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Breve</h1>

<%= render 'form', breve: @breve %>

<%= link_to 'Show', @breve %> |
<%= link_to 'Back', breves_path %>

app/views/books/index.html.erb
<div class="container clearfix">
  <div class="table articles  page-edito ">
    <section class="left-article table-cell">
      <!-- left-article -->
      <article class="clearfix edito">
        <div class="table">
          <div class="body-edito table-cell">
            <header>
              <h1 class='podcast-title'>Les brèves</h1>
            </header>
            <% form_tag books_path, :method => 'get' do %>
              <p>
                <%= text_field_tag :search, params[:search] %>
                <%= submit_tag "Search", :name => nil %>
              </p>
            <% end %>
          </div>
        </div>
      </article>
      <!-- last article -->
      <div class="last-post clearfix">
        <% @books.each do |book| %>
          <article class=" on" style="height: 296px;">
            <a href="<%= book.lien %>" class="">
              <div class="clearfixd">
                <img src="<%= book.image.url %>" alt="">
                <div class="infos-right">
                  <span class="cat"></span>
                  <h2><%= book.titre %></h2>
                  <p><span class="author"><%= book.intervenant.nom %></span>, créée le <%= book.created_at.strftime("%d-%m-%Y") %></p>
                </div>
              </div>
            </a>
            <a href="/books/<%= book.id %>" class="">
              <div class="entry-content">
                <div>
                  <p class="aerian">"<%= book.description.html_safe %>"</p>
                </div>
              </div>
              <span class="icon-top"><i class="sprite etat"></i></span>
            </a>
          </article>
          <br>
        <% end %>
        <div class="nav-article">                  
	        <%= paginate @books %>
	      </div>
        <div class="clearfix"></div>
        <!-- <div class="sep-art"></div> -->   
      </div>
      <!-- liste journal -->
      <div class="last-num">
        <ul class="clearfix">
          <li class="view-all"><%= link_to 'VOIR TOUS LES PODCASTS', podcasts_path %></li>
        </ul>
      </div>
    </section>
  </div>
</div>

app/views/books/show.html.erb
<% content_for :social do %>
  <meta property="og:title" content="<%= @book.titre %>">
  <meta property="og:description" content="@book.description.html_safe">
  <meta property="og:image" content="<%= @book.image.url %>" />
<% end %>

<div class="container clearfix">
  <div class="table articles  page-edito ">
    <section class="left-article table-cell">
      <!-- left-article -->
      <article class="clearfix edito">
        <div class="table">
          <div class="body-edito table-cell">
            <header>
              <h1 class='podcast-title'><%= @book.titre %></h1>
              <p class="author"><%= "Brève proposée par " + @book.intervenant.nom %> dans l'émission <%= @book.podcast.title %>, que vous pouvez écouter <%= link_to "ici.", @book.podcast %> ou ci-dessous.</p>
            </header>
          </div>
        </div>
      </article>
      <!-- last article -->
      <div class="last-post clearfix">
        <article class=" on" style="height: 296px;">
          <a href="<%= @book.lien %>" class="">
            <div class="clearfixd">
              <img src="<%= @book.image.url %>" alt="">
              <div class="infos-right">
                <span class="cat"></span>
                <h2><%= @book.titre %></h2>
                <p class="author"><%= @book.intervenant.nom %></p>
              </div>
            </div>
            <div class="entry-content">
              <div>
                <p class="aerian">"<%= @book.description.html_safe %>"</p>
              </div>
            </div>
            <span class="icon-top"><i class="sprite etat"></i></span>
          </a>
        </article>
        <br>
        <div class="clearfix"></div>
        <!-- <div class="sep-art"></div> -->   
      </div>
      <iframe src="<%= @book.podcast.lien %>/embed" style="width: 100%; height: 200px; border: 0 none;" scrolling="no"></iframe>
      <h3>Les autres brèves de l'émission :</h3>
      <div class="last-post clearfix">
        <% @book.podcast.books.each do |book| %>
        	<% if book != @book %>
	          <article class=" on" style="height: 296px;">
	            <a href="<%= book.lien %>" class="">
	              <div class="clearfixd">
	                <img src="<%= book.image.url %>" alt="">
	                <div class="infos-right">
	                  <span class="cat"></span>
	                  <h2><%= book.titre %></h2>
	                  <p class="author"><%= book.intervenant.nom %></p>
	                </div>
	              </div>
	              <div class="entry-content">
	                <div>
	                  <p class="aerian">"<%= book.description.html_safe %>"</p>
	                </div>
	              </div>
	              <span class="icon-top"><i class="sprite etat"></i></span>
	            </a>
	          </article>
          	<br>
          <% end %>
        <% end %>
        <div class="clearfix"></div>
        <!-- <div class="sep-art"></div> -->   
      </div>
      <!-- liste journal -->
      <div class="last-num">
        <ul class="clearfix">
          <li class="view-all"><%= link_to 'VOIR TOUTES LES BREVES', books_path %></li>
        </ul>
      </div>
    </section>
  </div>
</div>

app/views/charges/charges.html.erb
Merci

app/views/charges/thanks.html.erb
<div id="center_column">
  <div class="container page-authentification">
    <div class="ak-title">Merci</div>
    <div class="line-abo first with-padding">
      <!-- <div class="line-title red"><span class="number">1</span> Identiﬁez-vous</div> -->
      <div class="ak-login">

				Grâce à vous Le Nouvel esprit public est accessible à tous sur la toile et peut ainsi continuer à gagner des auditeurs.<br>
				Vous allez  recevoir un email confirmant votre soutien.<br>
        Pour annuler votre abonnement, écrivez-nous à contact.lenouvelespritpublic@gmail.com.<br>
      </div>
    </div>
  </div>
</div>
<div id="wrap-popup-contact"></div>
<div id="popup-contact">
  <div class="inner">
    <div class="close_contact" id="close_contact"><i class="icon-close"></i></div>
    <h3 class="title">CONTACTez-nous !</h3>
    <div class="table first">
      <div class="table-cell"> </div>
      <div class="table-cell"> </div>
    </div>
    <div class="table">
      <div class="table-cell">
        <div class="only-mobile alig-center">  </div>
        <div class="txt">
          <h2>RÉDACTION</h2>
          <br>
          <p>Pour contacter l'équipe du Nouvel Esprit public.</p>
        </div>
        <div class="align-center"><a href="mailto:contact.lenouvelespritpublic@gmail.com" class="ak-btn">NOUS ÉCRIRE</a></div>
      </div>
      <div class="table-cell">
        <div class="only-mobile alig-center"> </div>
        <div class="txt">
          <h2>SERVICE ABONNEMENT</h2>
          <br>
          <p>Pour gérer votre abonnement.&nbsp;</p>
        </div>
        <div class="align-center"><a href="mailto:contact.lenouvelespritpublic@gmail.com" class="ak-btn">NOUS CONTACTER</a></div>
      </div>
    </div>
  </div>
</div>