config/routes.rb
Rails.application.routes.draw do
  resources :kontildondits
  mount ForestLiana::Engine => '/forest'
  resources :podcasts
  resources :books
  resources :badas
  resources :abonnes
  resources :rubriques,  :path => "chroniques"
  get '/kitafetoi', to: 'kitafetois#index', as: :kitafetois
  resources :kitafetois
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'thematiques' => 'podcasts#thematiques', as: :thematiques
  get 'partners' => 'pages#partners', as: :partners
  get 'abonnement' => 'pages#abonnement', as: :abonnement
  get 'updatecard' => 'pages#updatecard', as: :updatecard
  get 'mentions' => 'pages#mentions', as: :mentions
  get '/intervenant/:id', to: 'intervenants#show', as: 'intervenant'
  resources :charges
  resources :updatecards
  get 'thanks', to: 'charges#thanks', as: 'thanks'
  get 'soutiens', to: 'pages#soutiens', as: 'soutiens'
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
  get 'lettre' => 'pages#lettre', as: :lettre
  get 'lettretest' => 'pages#lettretest', as: :lettretest
end

app/models/abonne.rb
class Abonne < ApplicationRecord
	has_many :intervenants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bada.rb
class Bada < ApplicationRecord
	belongs_to :podcast
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :podcast
	belongs_to :intervenant
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/intervenant.rb
class Intervenant < ApplicationRecord
	has_many :books
	has_many :podcasts
	has_many :abonnes
	has_many :rubriques
end

app/models/kitafetoi.rb
class Kitafetoi < ApplicationRecord
	has_many :intervenants
end

app/models/mailchimp.rb
class Mailchimp < ApplicationRecord
end

app/models/podcast.rb
class Podcast < ApplicationRecord
	has_many :books
	has_many :intervenants
end

app/models/public.rb
class Public < ApplicationRecord

	
end

app/models/rubrique.rb
class Rubrique < ApplicationRecord
	belongs_to :intervenant
end

app/controllers/abonnes_controller.rb
class AbonnesController < ApplicationController
  before_action :set_abonne, only: [:show, :edit, :update, :destroy]
  before_action :set_link

  def index
    @abonnes = Abonne.all.order(created_at: :desc).page(params[:page]).per(5)
  end

  def show
  end

  def new
    @abonne = Abonne.new
  end

  def edit
  end

  def create
    @abonne = Abonne.new(abonne_params)
    
    if @abonne.save
      redirect_to @abonne, notice: 'Podcast was successfully created.'
    else
      render :new
    end
  end

  def update
    if @abonne.update(abonne_params)
      redirect_to @abonne, notice: 'Podcast was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @abonne.destroy
    redirect_to pabonnes_url, notice: 'Podcast was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abonne
      @abonne = Abonne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def abonne_params
      params.require(:abonne).permit(:title, :lien, :title1, :intro1, :title2, :intro2)
    end

    def set_link
      @public_link = Public.where(live: true).order(created_at: :desc).first
    end

end

app/controllers/badas_controller.rb
class BadasController < ApplicationController
  before_action :set_bada, only: [:show, :edit, :update, :destroy]
  before_action :set_link

  def index
    @badas = Bada.all.includes(:podcast).order('podcasts.created_at desc').page(params[:page]).per(5)
  end

  def show
  end

  def new
    @bada = Bada.new
  end

  def edit
  end

  def create
    @bada = Bada.new(bada_params)
    
    if @bada.save
      redirect_to @bada, notice: 'Bada was successfully created.'
    else
      render :new
    end
  end

  def update
    if @bada.update(bada_params)
      redirect_to @bada, notice: 'Bada was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @bada.destroy
    redirect_to badas_url, notice: 'Bada was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bada
      @bada = Bada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bada_params
      params.require(:bada).permit(:title, :lien, :podcast_id, :transcript)
    end

    def set_link
      @public_link = Public.where(live: true).order(created_at: :desc).first
    end 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :set_link

  def index
    @books = Book.all.includes(:podcast).order('podcasts.created_at desc').page(params[:page]).per(12)
  end

  def show
    
  end

  def new
    @book = book.new
  end

  def edit
  end

  def create
    @book = book.new(book_params)
    
    if @book.save
      redirect_to @book, notice: 'book was successfully created.'
    else
      render :new
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: 'book was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:titre, :intervenant_id, :podcast_id, :description, :image)
    end

    def set_link
      @public_link = Public.where(live: true).order(created_at: :desc).first
    end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :set_link, :set_mailchimp


	def home
		@podcast = Podcast.all.order(created_at: :desc).first
	end
	
	def partners
	end

	def abonnement
	end

	def updatecard
	end

	def mentions
	end

	def soutiens
	end

	def lettre
	end

	def lettretest
	end

	def subscribed
    UserMailer.subscribe_confirmation(params[:email]).deliver
    UserMailer.subscribe(params[:email]).deliver
    redirect_to :action => "home"
	end

	def letsencrypt
	  render text: params[:id]+'.ylwsIZ1qM8410SY4fhGjVuvDfZoYpC6DvIEe4BSXSek'
	end

	private
    def set_link
      @public_link = Public.where(live: true).order(created_at: :desc).first
    end

    def set_mailchimp
      @mailchimp_link = Mailchimp.order(created_at: :desc).first
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/kontildits_helper.rb
module KontilditsHelper
end

app/helpers/kontildondits_helper.rb
module KontildonditsHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/rubriques_helper.rb
module RubriquesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<!--[if lt IE 7]> 
<html class="no-js lt-ie9 lt-ie8 lt-ie7 " lang="fr">
<![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8 ie7" lang="fr">
<![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9 ie8" lang="fr">
<![endif]-->
<!--[if gt IE 8]> 
<html class="no-js ie9" lang="fr">
<![endif]-->
<html lang="fr">
  <head>
    <meta charset="utf-8" />
    <title>Le Nouvel Esprit public - Peau de Caste</title>
    <meta name="description" content="Chaque dimanche, le Nouvel Esprit public éclaire certains éléments de l’actualité de la semaine écoulée." />
    <meta name="viewport" content="width=device-width, minimum-scale=0.25, maximum-scale=1.6, initial-scale=1.0" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <%= favicon_link_tag('favicon.jpg') %>
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:site_name" content="Le Nouvel Esprit public" />
    <%= yield :social %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      
      ga('create', 'UA-106121164-1', 'auto');
      ga('send', 'pageview');
    </script>

    <script type="text/javascript">
      var CUSTOMIZE_TEXTFIELD = 1;
      var FancyboxI18nClose = 'Fermer';
      var FancyboxI18nNext = 'Suivant';
      var FancyboxI18nPrev = 'Pr&eacute;c&eacute;dent';
      var ajax_allowed = true;
      var ajaxsearch = true;
      var baseDir = '';
      var baseUri = '';
      var blocksearch_type = 'top';
      var contentOnly = false;
      var customizationIdMessage = 'Personnalisation';
      var delete_txt = 'Supprimer';
      var displayList = false;
      var freeProductTranslation = 'Offert !';
      var freeShippingTranslation = 'Livraison gratuite !';
      var generated_date = 1508514712;
      var id_lang = 1;
      var img_dir = '';
      var instantsearch = false;
      var isGuest = 0;
      var isLogged = 0;
      var page_name = 'index';
      var placeholder_blocknewsletter = 'Saisissez votre adresse e-mail';
      var priceDisplayMethod = 0;
      var priceDisplayPrecision = 2;
      var quickView = true;
      var removingLinkText = 'supprimer cet article du panier';
      var roundMode = 2;
      var search_url = '';
      var static_token = '';
      var token = '';
      var usingSecureMode = true;
    </script>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
   
    <%= javascript_include_tag 'application' %>
    <script type="text/javascript" src="https://blockchain.info/Resources/js/pay-now-button.js"></script>

  </head>
  <body  id="<%= (action_name == 'home') ? 'index' : ''  %>" class="body lang_fr">
    <div class="layout">
      <div id="fixed-nav-top" class="clearfix">
        <div class="left desktop">
        </div>
        <div class="right">
          <div class="link-nav-top acount mobile">
            <a href="/abonnement" class="ak-log-in"><!-- <i class="ak-icon acount"> --></i> 
              <span>Soutenez-nous</span> 
            </a>
          </div>
          <div class="block-subscription">
            <a href="/abonnement" class="top"><span class="align-middle">Soutenez-nous</span> <!-- <i class="ico-journal"></i> --></a>
            <div class="ak-auth">
              <a href="/podcasts" id="open-form-login" class="ak-log-in">Les podcasts<!-- <i class="ak-icon acount"></i> --></a>
            </div>
          </div>
        </div>
      </div>
      <div id="main-nav-mobile" class="mobile">
        <div class="nav-m">
          <a href="#" class="logo-m"></a>
          <div class="burger" id="open-nav">
            <span></span>
          </div>
        </div>
        <div class="close-wrap" id="close-nav">
          <!-- Fermer le menu -->
          <div class="close clearfix">
            <svg version="1.1" id="Calque_1" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink" x="0px" y="0px"
              width="19.092px" height="19.092px" viewBox="0 0 19.092 19.092" enable-background="new 0 0 19.092 19.092" xml:space="preserve" class="right">
              <g>
                <rect x="-1.954" y="7.546" transform="matrix(0.7071 -0.7071 0.7071 0.7071 -3.9542 9.5462)" fill="#010101" width="23.001" height="4"/>
                <rect x="-1.954" y="7.546" transform="matrix(0.7071 0.7071 -0.7071 0.7071 9.5463 -3.954)" fill="#010101" width="23.001" height="4"/>
              </g>
            </svg>
          </div>
        </div>
        <div class="shadow-top mobile"></div>
      </div>
      <div id="main-nav">
        <%= link_to root_path, class: 'nav-top desktop' do %>
          <div class="top"></div>
          <div class="bottom credentials"></div>
        <% end %>
        <div class="main-menu">
          <div class="decouvert mobile">
            <a href="/abonnement" class="">soutenez-nous</a> <span>/</span> <a href="/podcasts">les podcasts</a>
          </div>
          <div class="inner-menu">
            <div class="wrap-menu">
              <ul>
                <li><%= link_to "Soutenez-nous", abonnement_path %></li>
                <li><a href="#" class="ak-open-contact">Ecoutez-nous</a></li>
                <li><a href="https://lenouvelespritpublic.us17.list-manage.com/subscribe?u=97b4e6ae6cc95aa343ac42282&id=fc98149f82">Recevoir le compendium</a></li>
                
                <!-- <li><a href="/lettre">Lettre d'information</a></li> -->
                <li><%= link_to "Les brèves", books_path %></li>   
                <li>
                  <% if @public_link %>
                    <%= link_to "Les émissions en public", @public_link.lien %>
                  <% end %>
                </li>
                <li><%= link_to "Les badas", badas_path %></li>
                <li><%= link_to "Les thématiques", thematiques_path %></li>
                <!-- <li>Lettre d'information</li> -->
                <!-- <li><a href="#">Nous contacter</a></li> -->
              </ul>
              <div class="hidden-menu">
                <ul>
                  <% if Podcast.all.last.kontildondit1 %>
                  <li><a href="<%= Podcast.all.where.not(pdf: [nil, ""]).last.pdf %>">Dernier Compendium</a></li>
                  <% else %>
                  
                  <% end %>
                  <li><a href="/lettre">Lettre d'information</a></li>
                  <li><%= link_to "Les chroniques", rubriques_path %></li>
                  <li><%= link_to "Les kitafétoi", kitafetois_path %></li>
                  
                  <li><%= link_to "L’équipe", root_path(anchor: 'equipe')  %></li>
                  <li><%= link_to "Les partenaires", partners_path %></li>
                  <li><%= link_to "Les soutiens", soutiens_path %></li>
                </ul>
              </div>
              <div id="open-menu"><i class="fa fa-plus"></i></div>
            </div>
            <div class="rs clearfix">
              <a href="https://www.facebook.com/philippe.meyer.501" target="_blank"><i class="fa fa-facebook"></i></a>
              <a href="https://twitter.com/LePhilippeMeyer" target="_blank"><i class="fa fa-twitter"></i></a>
              <a href="mailto:contact.lenouvelespritpublic@gmail.com" class="right"><i class="fa fa-envelope"></i></a>
            </div>
          </div>
        </div>
      </div>
      <div class="main-container">
        <%= yield %>
      </div>
      <div id="wrap-popup-contact"></div>
      <div id="popup-contact">
        <div class="inner">
          <div class="close_contact" id="close_contact"><i class="icon-close"></i></div>
          <h3 class="title">Abonnez-vous !</h3>
          <div class="table first">
            <div class="table-cell"> <img src="/assets/apple.svg" width="200" alt=""> </div>
            <div class="table-cell"> <img src="/assets/soundcloud.png" width="65" alt=""> </div>
          </div>
          <div class="table">
            <div class="table-cell">
              <div class="only-mobile alig-center"> <img src="" width="65" alt=""> </div>
              <div class="txt">
                <h2>ITUNES</h2>
                <br />
                <p>Le Nouvel Esprit Public est disponible sur iTunes</p>
              </div>
              <div class="align-center"><a href="https://itunes.apple.com/fr/podcast/le-nouvel-esprit-public/id1279728744?mt=2" class="ak-btn">JE M'ABONNE SUR ITUNES</a></div>
            </div>
            <div class="table-cell">
              <div class="only-mobile alig-center"> <img src="/assets/soundcloud.png" width="65" alt=""> </div>
              <div class="txt">
                <h2>SOUNDCLOUD</h2>
                <br />
                <p>Le Nouvel Esprit Public est aussi disponible sur Soundcloud</p>
              </div>
              <div class="align-center"><a href="https://soundcloud.com/user-102568040 " class="ak-btn">JE M'ABONNE SUR SOUNDCLOUD</a></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <footer id="footer" class="clearfix">
      <div class="right">
        <a href="/podcasts" class="lien-journal" onclick="ga('send', 'event', 'Lien journal', 'clicked', 'ACCÉDER AU JOURNAL');" >ACCÉDER AUX PODCASTS</a>
        <ul class="right-link">
          <!-- <li><a href="">FAQ</a></li> -->
          <li><%= link_to "MENTIONS LÉGALES", mentions_path %></li>
          <!-- <li><a href="">CGV</a></li> -->
        </ul>
      </div>
      <!-- <form class="nl left" id="newsletter_form" action="https://nouvelespritpublic.fr/themes/le1-v2/nl/mailchimp.php" method="post">
        <label>Newsletter </label>
        <div class="input">
          <input type="texte" name="email" class="email" autocomplete="off" placeholder="Votre e-mail">
          <button type="submit">
            <span class="btn-ok">ok</span>  
            <div class="spinner" style=""></div>
          </button>
        </div>
      </form> -->
      <div class="clearfix lien-journal-mobile">
        <a href="/podcasts" class="lien-journal " onclick="ga('send', 'event', 'Lien journal', 'clicked', 'ACCÉDER AU JOURNAL');">ACCÉDER AU PODCASTS</a>
      </div>
    </footer>
    <!-- <script src="//my.hellobar.com/" type="text/javascript" charset="utf-8" async="async"></script> -->
    
  </body>
</html>

app/views/pages/abonnement.html.erb
<div id="center_column">
  <div class="container page-authentification">
    <div class="ak-title">S'ABONNER</div>
    <div class="line-abo first with-padding">
      <!-- <div class="line-title red"><span class="number">1</span> Identiﬁez-vous</div> -->
      <div class="ak-login">
        <div class="table">
          <div class="table-cell">
            <!-- <span class="separator"></span> -->
            <div class="inner-login">
              <div class="title-row red">
                Le soutien mensuel défiscalisé
                <span>Le soutien ci-dessous est un soutien mensuel défiscalisé à 66% pour les particuliers, 60% pour les entreprises. Par exemple, un soutien de 30€ ne vous coûtera que 10 € par mois.</span>
                <br>

                  <a class="custom-dbox-popup" href="https://donorbox.org/le-nouvel-esprit-public" style="background: #9d3934 url(https://donorbox.org/images/white_logo.svg) no-repeat 45px;color: #fff;text-decoration: none;font-family: Verdana,sans-serif;display: inline-block;font-size: 16px;padding: 15px 45px;padding-left: 70px;-webkit-border-radius: 8px;-moz-border-radius: 8px;border-radius: 8px;">
                    Nous soutenir
                  </a>

                  <script type="text/javascript" defer src="https://donorbox.org/install-popup-button.js" id="donorbox-popup-button-installer"> </script>
                  <script> window.DonorBox = { widgetLinkClassName: 'custom-dbox-popup' } </script> 

                <div ></div><br>

                <span>Si vous êtes déjà soutien et que vous voulez augmentez votre contribution vous pouvez:</span>
                  <span>- Soit le faire dans votre espace personnel sur le site <a href="https://www.okpal.com/account/signin?next=https%3A%2F%2Fwww.okpal.com%2F">OK Pal</a> via l'onglet mes contributions</span>
                  <span>- Soit faire votre nouvelle contribution via l'onglet Nous soutenir sur notre site, et annuler votre ancienne contribution sur le site OK Pal toujours via l’onglet Mes contributions. Dans ce cas, votre contribution sera enregistrée sur le site Donorbox, nouvellement installé par J’Aime l’Info et qui permet de recevoir immédiatement le reçu de votre contribution</span>
                </span>
              </div>
            </div>
          </div>
          <div class="table-cell">
            <div class="inner-login">
              <div class="title-row red">
                Le soutien ponctuel défiscalisé
                <span>Pour nous soutenir ponctuellement, vous pouvez nous adresser :</span>
              </div>
              <div class="text center">
                <p>- un chèque libellé à l’ordre de :
                <p>Le Nouvel Esprit public J’aime l’Info<br>4 rue La Vrillière<br>75001 Paris</p>
              </div>


            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="wrap-popup-contact"></div>
  <div id="popup-contact">
    <div class="inner">
      <div class="close_contact" id="close_contact"><i class="icon-close"></i></div>
      <h3 class="title">Abonnez-vous !</h3>
      <div class="table first">
        <div class="table-cell"> <img src="/assets/apple.svg" width="200" alt=""> </div>
        <div class="table-cell"> <img src="/assets/soundcloud.png" width="65" alt=""> </div>
      </div>
      <div class="table">
        <div class="table-cell">
          <div class="only-mobile alig-center"> <img src="" width="65" alt=""> </div>
          <div class="txt">
            <h2>ITUNES</h2>
            <br />
            <p>Le Nouvel Esprit Public est disponible sur iTunes</p>
          </div>
          <div class="align-center"><a href="https://itunes.apple.com/fr/podcast/le-nouvel-esprit-public/id1279728744?mt=2" class="ak-btn">JE M'ABONNE SUR ITUNES</a></div>
        </div>
        <div class="table-cell">
          <div class="only-mobile alig-center"> <img src="/assets/soundcloud.png" width="65" alt=""> </div>
          <div class="txt">
            <h2>SOUNDCLOUD</h2>
            <br />
            <p>Le Nouvel Esprit Public est aussi disponible sur Soundcloud</p>
          </div>
          <div class="align-center"><a href="https://soundcloud.com/user-102568040 " class="ak-btn">JE M'ABONNE SUR SOUNDCLOUD</a></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/lettre.html.erb
<div class="container page-authentification">

  <span style="font-size: 27px;"><strong class="first">Nos lettres d'information</strong></span>
  <p>Vous trouverez ci-dessous nos communications envoyées dans notre newsletter, à laquelle vous pouvez vous abonner sur l'onglet en haut à gauche ci-dessous :</p>
  <div class="result">
    <div class="article-search archive">
      <iframe id="inlineFrameExample"
          title="Inline Frame Example"
          width="100%"
          height="800"
          src="<%= @mailchimp_link.lien %>">
      </iframe>
    </div>
  </div>
</div>

app/views/pages/mentions.html.erb
<div id="cms" class="container">
   <div class="rte">
      <h1><strong>MENTIONS LÉGALES</strong></h1>
      <p> </p>
      <p><strong> LE PHOENIX SASU au capital de 10.000 euros</strong></p>
      <p>RCS Paris B 799 483 953</p>
      <p><strong>Code activité</strong>&nbsp;: NAF 6391Z</p>
      <p><strong>Siège social</strong>&nbsp;: LLE PHOENIX SASU - 4 rue la Vrillière, 75001 PARIS</p>
      <p><strong>N° Siret</strong>&nbsp;: 832 360 101 00014</p>
      <p><strong>Président</strong>&nbsp;: Philippe MEYER</p>
      <p><strong>Directeur de la publication</strong>&nbsp;: Philippe MEYER</p>
      <p><strong>Hébergeur</strong>&nbsp;: HEROKU, INC., The Landmark @ One Market Street, Suite 300,  San Francisco CA 94105 (Etats-Unis) – téléphone : +448008085158</p>
      <p>&nbsp;</p>
   </div>
   <br>
</div>

app/views/pages/updatecard.html.erb
<div id="center_column">
  <div class="container page-authentification">
    <div class="ak-title">METTRE A JOUR SES INFORMATIONS</div>
    <div class="line-abo first with-padding">
      <!-- <div class="line-title red"><span class="number">1</span> Identiﬁez-vous</div> -->
      <div class="ak-login">
        <div class="table">
          <div class="table-cell">
            <!-- <span class="separator"></span> -->
            <div class="inner-login">
              <div class="title-row red">
                Vous souhaitez renouveler votre soutien sur la durée ?
                <span>Merci de votre soutien, pour mettre à jour votre abonnement, merci de préciser l’abonnement que vous soutenez. Tous les abonnements sont résiliables à tout moment par simple envoi d'un courriel à contact.lenouvelespritpublic@gmail.com. Un abonnement est le meilleur moyen durable de soutenir l'émission.</span>
              </div>
              <%= form_tag updatecards_path, id: 'login_form', class: 'box' do %>
                <script src="https://checkout.stripe.com/checkout.js"></script>
                <%= hidden_field_tag 'stripeToken' %>
                <%= hidden_field_tag 'stripeEmail' %>

                <div class="ak-form">
                  <div class="row-form form-ok">
                    <label for="passwd">Abonnement souhaité</label>
                    <select name="stripePlan" id= "stripeAmount" class="is_required validate account_input input">

                      <!-- <input type="radio" value="BASENEP2018">
                      <label for="BASENEP2018">Base - 5€ par mois</label>
                      <input type="radio" value="ACCOMPAGNEMENTNEP2018">
                      <label for="ACCOMPAGNEMENTNEP2018">Accompagnement - 10€ par mois</label>
                      <input type="radio" value="ENCOURAGEMENTNEP2018">
                      <label for="contactChoice1">Encouragement - 15€ par mois</label>
                      <input type="radio" value="PARRAINAGENEP2018">
                      <label for="contactChoice1">Parrainage - 30€ par mois</label> -->
                      <option value="ACCOMPAGNEMENTNEP2018">Accompagnement - 10€ par mois</option>
                      <option value="BASENEP2018">Base - 5€ par mois</option>
                      <option value="ENCOURAGEMENTNEP2018">Encouragement - 15€ par mois</option>
                      <option value="PARRAINAGENEP2018">Parrainage - 30€ par mois</option>
                      <option value="SOUTIENNEP2018">Soutien - 60€ par mois</option>
                    </select>                    
                  </div>
                  <div class="row-submit">
                    <button type="submit" id="SubmitLogin" name="SubmitLogin" class="ak-btn">Soutenir</button>
                  </div>
                </div>
                <script>
                  var handler = StripeCheckout.configure({
                    key: '<%= Rails.configuration.stripe[:publishable_key] %>',
                    locale: 'auto',
                    token: function(token, arg) {
                      document.getElementById("stripeToken").value = token.id;
                      document.getElementById("stripeEmail").value = token.email;
                      document.getElementById("login_form").submit();
                    }
                  });
                   document.getElementById('SubmitLogin').addEventListener('click', function(e) {
                    handler.open({
                      name: "Le Nouvel Esprit public",
                      description: "Je soutiens le Nouvel Esprit public.",
                      amount: parseInt(document.getElementById("stripeAmount").value),
                      currency: "eur"
                  });
                  e.preventDefault();
                  })
                </script>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="wrap-popup-contact"></div>
  <div id="popup-contact">
    <div class="inner">
      <div class="close_contact" id="close_contact"><i class="icon-close"></i></div>
      <h3 class="title">Abonnez-vous !</h3>
      <div class="table first">
        <div class="table-cell"> <img src="/assets/apple.svg" width="200" alt=""> </div>
        <div class="table-cell"> <img src="/assets/soundcloud.png" width="65" alt=""> </div>
      </div>
      <div class="table">
        <div class="table-cell">
          <div class="only-mobile alig-center"> <img src="" width="65" alt=""> </div>
          <div class="txt">
            <h2>ITUNES</h2>
            <br />
            <p>Le Nouvel Esprit Public est disponible sur iTunes</p>
          </div>
          <div class="align-center"><a href="https://itunes.apple.com/fr/podcast/le-nouvel-esprit-public/id1279728744?mt=2" class="ak-btn">JE M'ABONNE SUR ITUNES</a></div>
        </div>
        <div class="table-cell">
          <div class="only-mobile alig-center"> <img src="/assets/soundcloud.png" width="65" alt=""> </div>
          <div class="txt">
            <h2>SOUNDCLOUD</h2>
            <br />
            <p>Le Nouvel Esprit Public est aussi disponible sur Soundcloud</p>
          </div>
          <div class="align-center"><a href="https://soundcloud.com/user-102568040 " class="ak-btn">JE M'ABONNE SUR SOUNDCLOUD</a></div>
        </div>
      </div>
    </div>
  </div>
</div>